export const topRatedMovies = [
    '12 Angry Men',
    'Alien',
    "All About Eve",
    'American Beauty',
    'Amadeus',
    'American History X',
    "The Apartment",
    "Anne of Green Gables",
    "Barry Lyndon",
    "Before Sunrise",
    "Believe Me: The Abduction of Lisa McVey",
    "Black Beauty",
    "Bo Burnham: Inside",
    "Bo Burnham: Make Happy",
    "Bohemian Rhapsody",
    "Bound by Honor",
    "Catch Me If You Can",
    'City of God',
    'Casablanca',
    "Casino",
    "The Circus",
    'City Lights',
    "Coco",
    "Cruella",
    'Dangal',
    "The Deer Hunter",
    "Dial M for Murder",
    "A Dog's Journey",
    'Double Indemnity',
    "The Elephant Man",
    "Emancipation",
    'Eternal Sunshine of the Spotless Mind',
    'Fight Club',
    "Finch",
    "Flipped",
    "Ford v Ferrari",
    'Forrest Gump',
    'Full Metal Jacket',
    `Gabriel's Inferno`,
    `Gabriel's Inferno: Part II`,
    `Gabriel's Inferno: Part III`,
    "The General",
    "Ghosts",
    "Gifted",
    "Gone with the Wind",
    'Goodfellas',
    "Good Will Hunting",
    "The Grand Budapest Hotel",
    "Gran Torino",
    "Hannah Gadsby: Nanette",
    "Harry Potter and the Deathly Hallows: Part 2",
    "Harry Potter and the Prisoner of Azkaban",
    "The Help",
    "Hidden Figures",
    "How to Train Your Dragon: Homecoming",
    "The Imitation Game",
    "In a Heartbeat",
    'Inception',
    "It's a Wonderful Life",
    "Jojo Rabbit",
    "Judgment at Nuremberg",
    "Kill Bill: The Whole Bloody Affair",
    "Kill Bill: Vol. 1",
    "Kitbull",
    'Léon: The Professional',
    'Life Is Beautiful',
    "Lion",
    "Lock, Stock and Two Smoking Barrels",
    "Love, Simon",
    "Loving Vincent",
    "The Mitchells vs. the Machines",
    "Nobody",
    "On the Waterfront",
    "One Flew Over the Cuckoo's Nest",
    "One Week",
    "Palmer",
    "Paperman",
    "Paris, Texas",
    "Pink Floyd: The Wall",
    "Prayers for Bobby",
    "Pride & Prejudice",
    'Princess Mononoke',
    "Prisoners",
    'Pulp Fiction',
    "Purple Hearts",
    "Raging Bull",
    "The Red Shoes",
    "Redeeming Love",
    "Ron's Gone Wrong",
    "Room",
    "Rope",
    "Schindler's List",
    'Se7en',
    'Seven Samurai',
    "Sherlock Jr.",
    "Some Like It Hot",
    "Song of the Sea",
    "Star Wars",
    'Star Wars: Episode IV - A New Hope',
    "There Will Be Blood",
    "Three Billboards Outside Ebbing, Missouri",
    "Trainspotting",
    'The Dark Knight',
    'The Dark Knight Rises',
    'The Empire Strikes Back',
    "The Father",
    'The Godfather',
    'The Godfather Part II',
    "The Gold Rush",
    'The Good, the Bad and the Ugly',
    'The Lord of the Rings: The Return of the King',
    'The Lord of the Rings: The Fellowship of the Ring',
    'The Lord of the Rings: The Two Towers',
    'The Matrix',
    'The Shawshank Redemption',
    'The Silence of the Lambs',
    "Shutter Island",
    'Spirited Away',
    'Saving Private Ryan',
    "Scooby-Doo! Camp Scare",
    "Scooby-Doo! and KISS: Rock and Roll Mystery",
    "The Thing",
    "The Treasure of the Sierra Madre",
    "The Truman Show",
    'The Usual Suspects',
    "Where Hands Touch",
    "Wish Dragon",
    "The Wolf of Wall Street",
    'Once Upon a Time in the West',
    'Interstellar',
    'Psycho',
    'The Green Mile',
    'The Intouchables',
    'Modern Times',
    'Apocalypse Now',
    'Back to the Future',
    'Cinema Paradiso',
    'Citizen Kane',
    'The Departed',
    'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
    'Django Unchained',
    'Das Boot',
    'The Great Dictator',
    'Gladiator',
    'Grave of the Fireflies',
    'The Lives of Others',
    'The Lion King',
    'Memento',
    'North by Northwest',
    'Oldboy',
    'Once Upon a Time in America',
    'The Pianist',
    'Paths of Glory',
    'The Prestige',
    'Rear Window',
    'Raiders of the Lost Ark',
    'The Shining',
    'Sunset Boulevard',
    'Terminator 2: Judgment Day',
    'Witness for the Prosecution',
    'WALL·E',
    'Whiplash',
    'Vertigo',
    'Star Wars: Episode VI - Return of the Jedi',
    'Reservoir Dogs',
    'Braveheart',
    'M',
    'Requiem for a Dream',
    'Amélie',
    'A Clockwork Orange',
    'Like Stars on Earth',
    'Taxi Driver',
    'Lawrence of Arabia',
    'To Kill a Mockingbird',
    'Toy Story 3',
    'Logan',
    'The Sting',
    '2001: A Space Odyssey',
    "Singin' in the Rain",
    'Toy Story',
    'Bicycle Thieves',
    'The Kid',
    'Inglourious Basterds',
    'Snatch',
    '3 Idiots',
    'Monty Python and the Holy Grail',
    'The Boy, the Mole, the Fox and the Horse',
    'Primal: Tales of Savagery',
    'Spider-Man: Into the Spider-Verse',
    "Spider-Man: No Way Home",
    'Taylor Swift: Reputation Stadium Tour',
    'Dead Poets Society',
    'Puss in Boots: The Last Wish',
    'The Shop Around the Corner',
    'Wolfwalkers',
    'Five Feet Apart',
    'Clouds',
    "CODA",
    'Top Gun: Maverick',
    'Life in a Year',
    'Justice League Dark: Apokolips War',
    'Avengers: Endgame',
    'Steven Universe: The Movie',
    'Avengers: Infinity War',
    'Klaus',
    "Guillermo del Toro's Pinocchio",
    "Hamilton",
    "Green Book",
    "The Art of Racing in the Rain",
    "Hachi: A Dog's Tale",
    "Hacksaw Ridge",
    "Doctor Who: The Day of the Doctor",
    "Doctor Who: The Time of the Doctor",
    "Mortal Kombat Legends: Scorpion's Revenge",
    "Abraham Lincoln Vampire Hunter: The Great Calamity",
    "The Hate U Give",
    "Call Me by Your Name",
    "Joker",
    "Piper",
    "John Wick: Chapter 4",
    "Scarface",
    "Togo",
    "Wonder",
    "Michael Jackson's Thriller",
    "Soul",
    "Far from the Tree",
    "Zack Snyder's Justice League",
    "1917",
];