export const topRatedMovies = [
    "12 Angry Men",
    "12 Years a Slave",
    "1917",
    "2001: A Space Odyssey",
    "3 Idiots",
    "A Beautiful Mind",
    "A Bronx Tale",
    "A Clockwork Orange",
    "A Dog's Journey",
    "A Man Called Otto",
    "A Street Cat Named Bob",
    "A Woman Under the Influence",
    "About Time",
    "Abraham Lincoln Vampire Hunter: The Great Calamity",
    "Ace in the Hole",
    "Alien",
    "Aliens",
    "All About Eve",
    "All My Life",
    "All Quiet on the Western Front",
    "Amadeus",
    "Amélie",
    "American Beauty",
    "American History X",
    "Anatomy of a Murder",
    "Anne of Green Gables",
    "Apocalypse Now",
    "Avengers: Endgame",
    "Avengers: Infinity War",
    "Back to the Future",
    "Back to the Outback",
    "Barry Lyndon",
    "Batman: The Dark Knight Returns, Part 2",
    "Batman: Under the Red Hood",
    "Before Sunrise",
    "Before Sunset",
    "Believe Me: The Abduction of Lisa McVey",
    "Ben-Hur",
    "Bicycle Thieves",
    "Black Beauty",
    "Blade Runner",
    "Bo Burnham: Inside",
    "Bo Burnham: Make Happy",
    "Bo Burnham: What.",
    "Bohemian Rhapsody",
    "Bound by Honor",
    "Braveheart",
    "Brief Encounter",
    "Brokeback Mountain",
    "Call Me by Your Name",
    "Captain Fantastic",
    "Carlito's Way",
    "Casablanca",
    "Casino",
    "Catch Me If You Can",
    "Charm City Kings",
    "Chinatown",
    "Cinema Paradiso",
    "Citizen Kane",
    "City Lights",
    "City of God",
    "Clouds",
    "Coco",
    "CODA",
    "Coraline",
    "Cruella",
    "Dallas Buyers Club",
    "Dancer in the Dark",
    "Dances with Wolves",
    "Dangal",
    "Das Boot",
    "Dead Poets Society",
    "Dial M for Murder",
    "Django Unchained",
    "Doctor Who: A Christmas Carol",
    "Doctor Who: The Day of the Doctor",
    "Doctor Who: The Time of the Doctor",
    "Dog Day Afternoon",
    "Dogville",
    "Donnie Darko",
    "Double Indemnity",
    "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
    "Dune",
    "Emancipation",
    "Eternal Sunshine of the Spotless Mind",
    "Everything Everywhere All at Once",
    "Fail Safe",
    "Fantastic Mr. Fox",
    "Far from the Tree",
    "Fargo",
    "Feast",
    "Fight Club",
    "Finch",
    "Finding Nemo",
    "Five Feet Apart",
    "Flipped",
    "Ford v Ferrari",
    "Forrest Gump",
    "Freaks",
    "Freedom Writers",
    "Full Metal Jacket",
    "Gabriel's Inferno: Part II",
    "Gabriel's Inferno: Part III",
    "Gabriel's Inferno",
    "Ghosts",
    "Gifted Hands: The Ben Carson Story",
    "Gifted",
    "Girl in the Basement",
    "Gladiator",
    "Gone Girl",
    "Gone Mom: The Disappearance of Jennifer Dulos",
    "Gone with the Wind",
    "Good Will Hunting",
    "Goodfellas",
    "Gran Torino",
    "Grave of the Fireflies",
    "Green Book",
    "Guardians of the Galaxy",
    "Guillermo del Toro's Pinocchio",
    "Hachi: A Dog's Tale",
    "Hacksaw Ridge",
    "Hamilton",
    "Hannah Gadsby: Nanette",
    "Happy Halloween, Scooby-Doo!",
    "Harry Potter and the Deathly Hallows: Part 2",
    "Harry Potter and the Goblet of Fire",
    "Harry Potter and the Philosopher's Stone",
    "Harry Potter and the Prisoner of Azkaban",
    "Heat",
    "Her",
    "Hidden Figures",
    "Honor Society",
    "How to Train Your Dragon: Homecoming",
    "How to Train Your Dragon",
    "Hustle",
    "In a Heartbeat",
    "In the Name of the Father",
    "Inception",
    "Indiana Jones and the Last Crusade",
    "Inglourious Basterds",
    "Inner Workings",
    "Inside Out",
    "Interstellar",
    "Into the Wild",
    "Isle of Dogs",
    "It Happened One Night",
    "It's a Wonderful Life",
    "It's Such a Beautiful Day",
    "John Wick: Chapter 4",
    "Jojo Rabbit",
    "Joker",
    "Judgment at Nuremberg",
    "Jurassic Park",
    "Just Mercy",
    "Justice League Dark: Apokolips War",
    "Justice League: The Flashpoint Paradox",
    "Kill Bill: The Whole Bloody Affair",
    "Kill Bill: Vol. 1",
    "Kill Bill: Vol. 2",
    "Kitbull",
    "Klaus",
    "Knives Out",
    "L.A. Confidential",
    "La La Land",
    "La luna",
    "La migliore offerta",
    "Lawrence of Arabia",
    "Léon: The Professional",
    "Letter from an Unknown Woman",
    "Life in a Year",
    "Life Is Beautiful",
    "Like Stars on Earth",
    "Limelight",
    "Lion",
    "Little Women",
    "Lock, Stock and Two Smoking Barrels",
    "Logan",
    "Louis C.K.: Hilarious",
    "Louis C.K.: Live at the Beacon Theater",
    "Love, Rosie",
    "Love, Simon",
    "Loving Vincent",
    "Luca",
    "Luck",
    "M",
    "Marcel the Shell with Shoes On",
    "Mary and Max",
    "Me Before You",
    "Memento",
    "Michael Jackson's Thriller",
    "Midnight Sun",
    "Million Dollar Baby",
    "Mishima: A Life in Four Chapters",
    "Modern Times",
    "Monsieur Verdoux",
    "Monsters, Inc.",
    "Monty Python and the Holy Grail",
    "Mortal Kombat Legends: Battle of the Realms",
    "Mortal Kombat Legends: Scorpion's Revenge",
    "Mr. Nobody",
    "Mr. Smith Goes to Washington",
    "Mulan",
    "Mulholland Dr.",
    "Mulholland Drive",
    "My Little Pony: A New Generation",
    "My Policeman",
    "Network",
    "No Country for Old Men",
    "Nobody",
    "North by Northwest",
    "Notorious",
    "Oldboy",
    "On the Waterfront",
    "Once Upon a Time in America",
    "Once Upon a Time in the West",
    "One Flew Over the Cuckoo's Nest",
    "One Week",
    "Palmer",
    "Paper Moon",
    "Paperman",
    "Papillon",
    "Paris, Texas",
    "Partly Cloudy",
    "Paths of Glory",
    "Pink Floyd: The Wall",
    "Piper",
    "Pirates of the Caribbean: The Curse of the Black Pearl",
    "Prayers for Bobby",
    "Presto",
    "Prey",
    "Pride & Prejudice",
    "Primal: Tales of Savagery",
    "Princess Mononoke",
    "Prisoners",
    "Psycho",
    "Pulp Fiction",
    "Purple Hearts",
    "Puss in Boots: The Last Wish",
    "Raging Bull",
    "Raiders of the Lost Ark",
    "Ratatouille",
    "Raya and the Last Dragon",
    "Rear Window",
    "Rebecca",
    "Redeeming Love",
    "Regular Show: The Movie",
    "Requiem for a Dream",
    "Reservoir Dogs",
    "Return of the Jedi",
    "Rio Bravo",
    "Rocky",
    "Roman Holiday",
    "Ron's Gone Wrong",
    "Room",
    "Rope",
    "Rosemary's Baby",
    "Safety Last!",
    "Saving Private Ryan",
    "Scarface",
    "Schindler's List",
    "Scooby-Doo! Abracadabra-Doo",
    "Scooby-Doo! and KISS: Rock and Roll Mystery",
    "Scooby-Doo! and the Curse of the 13th Ghost",
    "Scooby-Doo! and the Goblin King",
    "Scooby-Doo! and the Samurai Sword",
    "Scooby-Doo! Camp Scare",
    "Se7en",
    "Seven Samurai",
    "Shelter",
    "Sherlock Jr.",
    "Sherlock: The Abominable Bride",
    "Shutter Island",
    "Sing 2",
    "Sing Street",
    "Singin' in the Rain",
    "Snatch",
    "Some Like It Hot",
    "Song of the Sea",
    "Soul",
    "Spider-Man: Into the Spider-Verse",
    "Spider-Man: No Way Home",
    "Spirited Away",
    "Spotlight",
    "Stand by Me",
    "Star Wars: Episode IV - A New Hope",
    "Star Wars: Episode VI - Return of the Jedi",
    "Star Wars",
    "Steven Universe: The Movie",
    "Straight Outta Compton",
    "Straight Outta Nowhere: Scooby-Doo! Meets Courage the Cowardly Dog",
    "Sunrise: A Song of Two Humans",
    "Sunset Boulevard",
    "Taxi Driver",
    "Taylor Swift: Reputation Stadium Tour",
    "Teen Titans Go! vs. Teen Titans",
    "Terminator 2: Judgment Day",
    "Tetris",
    "The Apartment",
    "The Art of Racing in the Rain",
    "The Best Years of Our Lives",
    "The Big Lebowski",
    "The Boy in the Striped Pyjamas",
    "The Boy Who Harnessed the Wind",
    "The Boy, the Mole, the Fox and the Horse",
    "The Breadwinner",
    "The Bridge on the River Kwai",
    "The Cameraman",
    "The Circus",
    "The Cure",
    "The Dark Knight Rises",
    "The Dark Knight",
    "The Deer Hunter",
    "The Departed",
    "The Elephant Man",
    "The Empire Strikes Back",
    "The Fabelmans",
    "The Father",
    "The General",
    "The Godfather Part II",
    "The Godfather",
    "The Gold Rush",
    "The Good, the Bad and the Ugly",
    "The Grand Budapest Hotel",
    "The Grapes of Wrath",
    "The Great Dictator",
    "The Great Escape",
    "The Greatest Showman",
    "The Green Mile",
    "The Hate U Give",
    "The Help",
    "The Imitation Game",
    "The Intouchables",
    "The Iron Giant",
    "The Kid",
    "The King of Comedy",
    "The Lion King",
    "The Lives of Others",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Lord of the Rings: The Return of the King",
    "The Lord of the Rings: The Two Towers",
    "The Man Who Shot Liberty Valance",
    "The Matrix",
    "The Miracle Worker",
    "The Mitchells vs. the Machines",
    "The Night of the Hunter",
    "The Nightmare Before Christmas",
    "The Normal Heart",
    "The Notebook",
    "The Perks of Being a Wallflower",
    "The Pianist",
    "The Prestige",
    "The Pursuit of Happyness",
    "The Red Shoes",
    "The Shawshank Redemption",
    "The Shining",
    "The Shop Around the Corner",
    "The Silence of the Lambs",
    "The Sixth Sense",
    "The Sting",
    "The Theory of Everything",
    "The Thing",
    "The Third Man",
    "The Tomorrow War",
    "The Treasure of the Sierra Madre",
    "The Truman Show",
    "The Usual Suspects",
    "The Wolf of Wall Street",
    "There Will Be Blood",
    "Thirteen Lives",
    "Three Billboards Outside Ebbing, Missouri",
    "Titanic",
    "To Be or Not to Be",
    "To Kill a Mockingbird",
    "Togo",
    "Top Gun: Maverick",
    "Toy Story 3",
    "Toy Story",
    "Trainspotting",
    "Unforgiven",
    "Up",
    "Us Again",
    "V for Vendetta",
    "Vertigo",
    "Vincent",
    "WALL·E",
    "War Room",
    "Warrior",
    "We Bare Bears: The Movie",
    "What Ever Happened to Baby Jane?",
    "Where Hands Touch",
    "Whiplash",
    "Who's Afraid of Virginia Woolf?",
    "Wish Dragon",
    "Witness for the Prosecution",
    "Wolfwalkers",
    "Wonder",
    "Words on Bathroom Walls",
    "World of Tomorrow",
    "Young Frankenstein",
    "Zack Snyder's Justice League",
];