export const topRatedMovies = [
    '12 Angry Men',
    'Alien',
    "All About Eve",
    'American Beauty',
    'Amadeus',
    'American History X',
    "The Apartment",
    "Anne of Green Gables",
    "Believe Me: The Abduction of Lisa McVey",
    "Black Beauty",
    "Bo Burnham: Inside",
    "Bo Burnham: Make Happy",
    "Bound by Honor",
    'City of God',
    'Casablanca',
    'City Lights',
    "Coco",
    "Cruella",
    'Dangal',
    'Double Indemnity',
    "The Elephant Man",
    'Eternal Sunshine of the Spotless Mind',
    'Fight Club',
    'Forrest Gump',
    'Full Metal Jacket',
    `Gabriel's Inferno`,
    `Gabriel's Inferno: Part II`,
    `Gabriel's Inferno: Part III`,
    "Gifted",
    'Goodfellas',
    "Good Will Hunting",
    "The Grand Budapest Hotel",
    "Hannah Gadsby: Nanette",
    "Harry Potter and the Deathly Hallows: Part 2",
    "The Help",
    "Hidden Figures",
    "How to Train Your Dragon: Homecoming",
    'Inception',
    "It's a Wonderful Life",
    "Jojo Rabbit",
    'Léon: The Professional',
    'Life Is Beautiful',
    "Lion",
    "Lock, Stock and Two Smoking Barrels",
    "Love, Simon",
    "Nobody",
    "One Flew Over the Cuckoo's Nest",
    "Paris, Texas",
    "Prayers for Bobby",
    "Pride & Prejudice",
    'Princess Mononoke',
    "Prisoners",
    'Pulp Fiction',
    "Purple Hearts",
    "Schindler's List",
    'Se7en',
    'Seven Samurai',
    "Sherlock Jr.",
    "Some Like It Hot",
    "Star Wars",
    'Star Wars: Episode IV - A New Hope',
    "There Will Be Blood",
    "Three Billboards Outside Ebbing, Missouri",
    'The Dark Knight',
    'The Dark Knight Rises',
    'The Empire Strikes Back',
    "The Father",
    'The Godfather',
    'The Godfather Part II',
    'The Good, the Bad and the Ugly',
    'The Lord of the Rings: The Return of the King',
    'The Lord of the Rings: The Fellowship of the Ring',
    'The Lord of the Rings: The Two Towers',
    'The Matrix',
    'The Shawshank Redemption',
    'The Silence of the Lambs',
    "Shutter Island",
    'Spirited Away',
    'Saving Private Ryan',
    "Scooby-Doo! and KISS: Rock and Roll Mystery",
    "The Truman Show",
    'The Usual Suspects',
    'Once Upon a Time in the West',
    'Interstellar',
    'Psycho',
    'The Green Mile',
    'The Intouchables',
    'Modern Times',
    'Apocalypse Now',
    'Back to the Future',
    'Cinema Paradiso',
    'Citizen Kane',
    'The Departed',
    'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
    'Django Unchained',
    'Das Boot',
    'The Great Dictator',
    'Gladiator',
    'Grave of the Fireflies',
    'The Lives of Others',
    'The Lion King',
    'Memento',
    'North by Northwest',
    'Oldboy',
    'Once Upon a Time in America',
    'The Pianist',
    'Paths of Glory',
    'The Prestige',
    'Rear Window',
    'Raiders of the Lost Ark',
    'The Shining',
    'Sunset Boulevard',
    'Terminator 2: Judgment Day',
    'Witness for the Prosecution',
    'WALL·E',
    'Whiplash',
    'Vertigo',
    'Star Wars: Episode VI - Return of the Jedi',
    'Reservoir Dogs',
    'Braveheart',
    'M',
    'Requiem for a Dream',
    'Amélie',
    'A Clockwork Orange',
    'Like Stars on Earth',
    'Taxi Driver',
    'Lawrence of Arabia',
    'To Kill a Mockingbird',
    'Toy Story 3',
    'Logan',
    'The Sting',
    '2001: A Space Odyssey',
    "Singin' in the Rain",
    'Toy Story',
    'Bicycle Thieves',
    'The Kid',
    'Inglourious Basterds',
    'Snatch',
    '3 Idiots',
    'Monty Python and the Holy Grail',
    'The Boy, the Mole, the Fox and the Horse',
    'Primal: Tales of Savagery',
    'Spider-Man: Into the Spider-Verse',
    'Taylor Swift: Reputation Stadium Tour',
    'Dead Poets Society',
    'Puss in Boots: The Last Wish',
    'The Shop Around the Corner',
    'Wolfwalkers',
    'Five Feet Apart',
    'Clouds',
    'Top Gun: Maverick',
    'Life in a Year',
    'Justice League Dark: Apokolips War',
    'Avengers: Endgame',
    'Steven Universe: The Movie',
    'Avengers: Infinity War',
    'Klaus',
    "Guillermo del Toro's Pinocchio",
    "Hamilton",
    "Green Book",
    "The Art of Racing in the Rain",
    "Hacksaw Ridge",
    "Doctor Who: The Day of the Doctor",
    "Mortal Kombat Legends: Scorpion's Revenge",
    "Abraham Lincoln Vampire Hunter: The Great Calamity",
    "The Hate U Give",
    "Call Me by Your Name",
    "Joker",
    "Piper",
    "John Wick: Chapter 4",
    "Scarface",
    "Togo",
    "Wonder",
    "Michael Jackson's Thriller",
    "Soul",
    "Far from the Tree",
    "Zack Snyder's Justice League",
];